### ISSUE TITLE
3person omok issues

### ISSUE THREAD

**Issue by BaeSooBeum** [BaeSooBeum/omok-2#1]
I think,,,,

내생각엔 3인오목은 돌의 색을 조금더 구분되게 바꿀 필요가 있을것같아...
그리고 게임이 안끝나기가 쉬워서 3인사목도 구현해보는것은 어떨까??

**Comment by crayola1331** [comment]
- 오목의 흑돌과 백돌은 너무 상징성이 강한 색깔이라 두가지는 가져가야 될것같은데, 회색 이외의 색중에 회색보다 조화로운 색이 있다면 바꿔도 좋을 것 같아요.
하지만 아직까지 시도 해본것 중엔 회색이 제일 나은 것같네요.

- 저도 3인 오목을 보면서 끝나기 힘들 것 같다는 생각이 들었네요. 이 부분은 완전히 동의 합니다.

**Comment by BaeSooBeum** [comment]
그러면 3인 4목은 어떨까요? 이 부분은 우리가 직접 오목을 해볼 필요가 있을것같아요!

테스트를 해봅시다!!!

**Comment by BaeSooBeum** [comment]
색상 변경없이 진행 결정

완료.
